In [ ]:
import pandas as pd
import numpy as np

credits=pd.read_csv("tmdb_5000_credits.csv")
movies=pd.read_csv("tmdb_5000_movies.csv")

movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits.head(15)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,559,Spider-Man 3,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,38757,Tangled,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,99861,Avengers: Age of Ultron,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,767,Harry Potter and the Half-Blood Prince,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,209112,Batman v Superman: Dawn of Justice,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."
10,1452,Superman Returns,"[{""cast_id"": 3, ""character"": ""Superman / Clark...","[{""credit_id"": ""553bef6a9251416874003c8f"", ""de..."
11,10764,Quantum of Solace,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe43b29251416c7501aa63"", ""de..."
12,58,Pirates of the Caribbean: Dead Man's Chest,"[{""cast_id"": 37, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""52fe4211c3a36847f8001873"", ""de..."
13,57201,The Lone Ranger,"[{""cast_id"": 4, ""character"": ""Tonto"", ""credit_...","[{""credit_id"": ""52fe4928c3a36847f818be95"", ""de..."
14,49521,Man of Steel,"[{""cast_id"": 2, ""character"": ""Clark Kent / Kal...","[{""credit_id"": ""52fe4799c3a36847f813e667"", ""de..."

In [ ]:
credits.head(1)["crew"].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [ ]:
print(type(movies))
print(type(credits))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
movies.merge(credits,on="title")

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [ ]:
combined=movies.merge(credits,on="title")

In [ ]:
combined.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
combined["original_language"].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
id       2
cs       2
ta       2
ro       2
ar       2
te       1
hu       1
xx       1
af       1
is       1
tr       1
vi       1
pl       1
nb       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [ ]:
com=combined[["genres","id","keywords","title","cast","crew","overview"]]

In [ ]:
com.head(5)

,genres,id,keywords,title,cast,crew,overview
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [ ]:
com.isnull().sum()

genres      0
id          0
keywords    0
title       0
cast        0
crew        0
overview    3
dtype: int64

In [ ]:
com.dropna(inplace=True)

<ipython-input-13-29d9149aee90>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com.dropna(inplace=True)

In [ ]:
com.isnull().sum()

genres      0
id          0
keywords    0
title       0
cast        0
crew        0
overview    0
dtype: int64

In [ ]:
com.duplicated().sum()

np.int64(0)

In [ ]:
com["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
com["keywords"][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [ ]:
import ast

In [ ]:
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i["name"])
  return L

In [ ]:
com["genres"]=com["genres"].apply(convert)

<ipython-input-20-cd6dd4ba47f3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["genres"]=com["genres"].apply(convert)

In [ ]:
com["keywords"]=com["keywords"].apply(convert)

<ipython-input-21-f45e92b9f49a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["keywords"]=com["keywords"].apply(convert)

In [ ]:
com

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[united states–mexico barrier, legs, arms, pap...",El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",El Mariachi just wants to play his guitar and ...
4805,"[Comedy, Romance]",72766,[],Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",A newlywed couple's honeymoon is upended by th...
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[date, love at first sight, narration, investi...","Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,[],126186,[],Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",When ambitious New York attorney Sam is sent t...
4808,[Documentary],25975,"[obsession, camcorder, crush, dream girl]",My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",Ever since the second grade when he first saw ...

In [ ]:
com["cast"][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [ ]:
com["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [ ]:
def convert2(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
     L.append(i["name"])
     counter+=1
    else:
      break
  return L

In [ ]:
com["cast"]=com["cast"].apply(convert2)

<ipython-input-26-66a107f9b8f8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["cast"]=com["cast"].apply(convert2)

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [ ]:
def fetch(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i["job"]=="Director":
     L.append(i["name"])
     break
  return L

In [ ]:
com["crew"]=com["crew"].apply(fetch)

<ipython-input-29-66b568f99c69>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["crew"]=com["crew"].apply(fetch)

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Following the death of District Attorney Harve...
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"John Carter is a war-weary, former military ca..."

In [ ]:
com["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
com["overview"]=com["overview"].apply(lambda x:x.split())

<ipython-input-32-fb50aa5f421b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["overview"]=com["overview"].apply(lambda x:x.split())

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
com["genres"]=com['genres'].apply(lambda x:[i.replace(" ","") for i in x])

<ipython-input-34-64d6c3ae2136>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["genres"]=com['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
com["genres"]=com['genres'].apply(lambda x:[i.replace(" ","") for i in x])
com["keywords"]=com['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
com["cast"]=com['cast'].apply(lambda x:[i.replace(" ","") for i in x])
com["crew"]=com['crew'].apply(lambda x:[i.replace(" ","") for i in x])

<ipython-input-36-cc2719d364f2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["genres"]=com['genres'].apply(lambda x:[i.replace(" ","") for i in x])
<ipython-input-36-cc2719d364f2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["keywords"]=com['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
<ipython-input-36-cc2719d364f2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["cast"]=com['cast'].apply(lambda x:[i.replace(" ","") for i in x])
<ipython-input-36-cc2719d364f2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["crew"]=com['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
com.loc["tags"]=com["overview"]+com["genres"]+com["keywords"]+com["cast"]+com["crew"]

<ipython-input-38-f8969c2b9f6b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com.loc["tags"]=com["overview"]+com["genres"]+com["keywords"]+com["cast"]+com["crew"]

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995.0,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285.0,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647.0,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026.0,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529.0,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
print(com.columns)

Index(['genres', 'id', 'keywords', 'title', 'cast', 'crew', 'overview'], dtype='object')

In [ ]:
com["tags"]=com["overview"]+com["genres"]+com["keywords"]+com["cast"]+com["crew"]

<ipython-input-41-fe96df5e4095>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  com["tags"]=com["overview"]+com["genres"]+com["keywords"]+com["cast"]+com["crew"]

In [ ]:
com.head()

,genres,id,keywords,title,cast,crew,overview,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995.0,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285.0,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d...","[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647.0,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send...","[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026.0,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney...","[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529.0,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili...","[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
newdf=com[['id',"title","tags"]]

In [ ]:
newdf.head()

,id,title,tags
0,19995.0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285.0,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647.0,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026.0,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529.0,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
newdf["tags"][3]

['Following',
 'the',
 'death',
 'of',
 'District',
 'Attorney',
 'Harvey',
 'Dent,',
 'Batman',
 'assumes',
 'responsibility',
 'for',
 "Dent's",
 'crimes',
 'to',
 'protect',
 'the',
 'late',
 "attorney's",
 'reputation',
 'and',
 'is',
 'subsequently',
 'hunted',
 'by',
 'the',
 'Gotham',
 'City',
 'Police',
 'Department.',
 'Eight',
 'years',
 'later,',
 'Batman',
 'encounters',
 'the',
 'mysterious',
 'Selina',
 'Kyle',
 'and',
 'the',
 'villainous',
 'Bane,',
 'a',
 'new',
 'terrorist',
 'leader',
 'who',
 'overwhelms',
 "Gotham's",
 'finest.',
 'The',
 'Dark',
 'Knight',
 'resurfaces',
 'to',
 'protect',
 'a',
 'city',
 'that',
 'has',
 'branded',
 'him',
 'an',
 'enemy.',
 'Action',
 'Crime',
 'Drama',
 'Thriller',
 'dccomics',
 'crimefighter',
 'terrorist',
 'secretidentity',
 'burglar',
 'hostagedrama',
 'timebomb',
 'gothamcity',
 'vigilante',
 'cover-up',
 'superhero',
 'villainess',
 'tragichero',
 'terrorism',
 'destruction',
 'catwoman',
 'catburglar',
 'imax',
 'flood',
 'criminalunderworld',
 'batman',
 'ChristianBale',
 'MichaelCaine',
 'GaryOldman',
 'ChristopherNolan']

In [ ]:
newdf["tags"] = newdf["tags"].apply(lambda x: "  ".join(x) if isinstance(x, list) else str(x))

<ipython-input-46-52bafa3a4a2f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf["tags"] = newdf["tags"].apply(lambda x: "  ".join(x) if isinstance(x, list) else str(x))

In [ ]:
newdf["tags"][0]

'In  the  22nd  century,  a  paraplegic  Marine  is  dispatched  to  the  moon  Pandora  on  a  unique  mission,  but  becomes  torn  between  following  orders  and  protecting  an  alien  civilization.  Action  Adventure  Fantasy  ScienceFiction  cultureclash  future  spacewar  spacecolony  society  spacetravel  futuristic  romance  space  alien  tribe  alienplanet  cgi  marine  soldier  battle  loveaffair  antiwar  powerrelations  mindandsoul  3d  SamWorthington  ZoeSaldana  SigourneyWeaver  JamesCameron'

In [ ]:
newdf["tags"]=newdf["tags"].apply(lambda x:x.lower())

<ipython-input-48-84927a1849bd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf["tags"]=newdf["tags"].apply(lambda x:x.lower())

In [ ]:
newdf["tags"][0]

'in  the  22nd  century,  a  paraplegic  marine  is  dispatched  to  the  moon  pandora  on  a  unique  mission,  but  becomes  torn  between  following  orders  and  protecting  an  alien  civilization.  action  adventure  fantasy  sciencefiction  cultureclash  future  spacewar  spacecolony  society  spacetravel  futuristic  romance  space  alien  tribe  alienplanet  cgi  marine  soldier  battle  loveaffair  antiwar  powerrelations  mindandsoul  3d  samworthington  zoesaldana  sigourneyweaver  jamescameron'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words="english")

vectors=cv.fit_transform(newdf['tags']).toarray()

In [ ]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.set_printoptions(threshold=np.inf)

In [ ]:
cv.get_feature_names_out()

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '18', '18th', '19', '1930s', '1940s', '1950s', '1960s',
       '1970s', '1980', '1980s', '1985', '1990s', '1999', '19th',
       '19thcentury', '20', '200', '2003', '2009', '20th', '21st', '24',
       '25', '30', '300', '3d', '40', '50', '500', '60', '60s', '70',
       'aaron', 'aaroneckhart', 'abandoned', 'abducted', 'abigailbreslin',
       'abilities', 'ability', 'able', 'aboard', 'abuse', 'abusive',
       'academy', 'accept', 'accepted', 'accepts', 'access', 'accident',
       'accidental', 'accidentally', 'accompanied', 'accomplish',
       'account', 'accountant', 'accused', 'ace', 'achieve', 'act',
       'acting', 'action', 'actionhero', 'actions', 'activist',
       'activities', 'activity', 'actor', 'actors', 'actress', 'acts',
       'actual', 'actually', 'adam', 'adams', 'adamsandler',
       'adamshankman', 'adaptation', 'adapted', 'addict', 'addicted',
       'addiction', 'adolescence', 'adopt', 'adopted', 'adoption',
       'adopts', 'adrienbrody', 'adult', 'adultery', 'adulthood',
       'adults', 'advantage', 'adventure', 'adventures', 'advertising',
       'advice', 'affair', 'affairs', 'affection', 'affections',
       'afghanistan', 'africa', 'african', 'africanamerican',
       'aftercreditsstinger', 'afterlife', 'aftermath', 'age', 'aged',
       'agedifference', 'agency', 'agenda', 'agent', 'agents',
       'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead', 'aid',
       'aided', 'aids', 'ailing', 'air', 'airplane', 'airplanecrash',
       'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert',
       'alcohol', 'alcoholic', 'alcoholism', 'alecbaldwin', 'alex',
       'alfredhitchcock', 'ali', 'alice', 'alien', 'alieninvasion',
       'alienlife', 'aliens', 'alike', 'alive', 'allen', 'alliance',
       'allied', 'allies', 'allow', 'allowing', 'allows', 'ally',
       'alongside', 'alpacino', 'alpha', 'alter', 'alternate',
       'alternative', 'alyssa', 'alzheimer', 'amanda', 'amandapeet',
       'amandaseyfried', 'amateur', 'amazing', 'amazon', 'ambassador',
       'ambition', 'ambitious', 'ambulance', 'ambush', 'america',
       'american', 'americanabroad', 'americancivilwar',
       'americanfootball', 'americanfootballplayer', 'americans', 'amid',
       'amidst', 'amnesia', 'amp', 'amsterdam', 'amusement',
       'amusementpark', 'amy', 'amyadams', 'amysmart', 'ana', 'anakin',
       'analyst', 'anarchiccomedy', 'ancient', 'ancientrome',
       'ancientworld', 'anderson', 'andiemacdowell', 'andrew', 'android',
       'andy', 'andygarcía', 'angel', 'angela', 'angelabassett',
       'angeles', 'angelinajolie', 'angels', 'anger', 'anglee', 'angry',
       'animal', 'animalattack', 'animalhorror', 'animals', 'animated',
       'animation', 'anime', 'anjelicahuston', 'ann', 'anna', 'annabelle',
       'annafaris', 'annakendrick', 'anne', 'annehathaway', 'annemoss',
       'annettebening', 'annie', 'anniversary', 'announces', 'annual',
       'anonymity', 'answer', 'answers', 'ant', 'antarctic', 'anthology',
       'anthony', 'anthonyanderson', 'anthonyhopkins', 'anthonymackie',
       'anthropomorphism', 'anti', 'antics', 'antihero', 'antoinefuqua',
       'antoniobanderas', 'antonyelchin', 'apart', 'apartheid',
       'apartment', 'ape', 'apes', 'apocalypse', 'apocalyptic',
       'apparent', 'apparently', 'appear', 'appears', 'apple',
       'appointed', 'apprentice', 'approach', 'approaches', 'approaching',
       'april', 'aquarium', 'arab', 'arch', 'archaeologist', 'archeology',
       'archer', 'architect', 'arctic', 'area', 'aren', 'arena',
       'argument', 'arise', 'aristocrat', 'armed', 'arms', 'army',
       'arnold', 'arnoldschwarzenegger', 'arrangedmarriage', 'arrest',
       'arrested', 'arrival', 'arrive', 'arrives', 'arriving', 'arrogant',
       'art', 'arthur', 'article', 'artificial', 'artificialintelligence',
       'artist', 'artistic', 'artists', 'arts', 'ashley', 'ashleyjudd',
       'ashtonkutcher', 'asia', 'asian', 'aside', 'ask', 'asked',
       'asking', 'asks', 'aspirations', 'aspiring', 'assassin',
       'assassinate', 'assassination', 'assassins', 'assault', 'assigned',
       'assignment', 'assistant', 'assumes', 'asteroid', 'astronaut',
       'astronauts', 'asylum', 'atheist', 'athlete', 'atomicbomb',
       'attack', 'attacked', 'attacks', 'attempt', 'attempting',
       'attempts', 'attending', 'attends', 'attention', 'attitude',
       'attorney', 'attracted', 'attraction', 'attractive', 'audience',
       'audiences', 'audition', 'august', 'aunt', 'austin', 'australia',
       'australian', 'author', 'authorities', 'authority', 'autism',
       'auto', 'avenge', 'average', 'avoid', 'awaits', 'awakens', 'award',
       'away', 'awry', 'ax', 'babe', 'baby', 'bachelor', 'backdrop',
       'background', 'backgrounds', 'bad', 'bag', 'bahamas', 'bail',
       'balance', 'ball', 'ballet', 'baltimore', 'band', 'bandits',
       'bangkok', 'banished', 'bank', 'banker', 'bankrobber',
       'bankrobbery', 'bar', 'barely', 'bargained', 'barn', 'barney',
       'barry', 'barrylevinson', 'bars', 'base', 'baseball', 'based',
       'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel',
       'basedonplay', 'basedonstagemusical', 'basedontrueevents',
       'basedontruestory', 'basedontvseries', 'basedonvideogame',
       'basedonyoungadultnovel', 'basement', 'basketball', 'batman',
       'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach',
       'bear', 'bears', 'beast', 'beasts', 'beat', 'beating', 'beautiful',
       'beautifulwoman', 'beauty', 'becky', 'becominganadult', 'bed',
       'bedroom', 'beer', 'befriends', 'began', 'begin', 'beginning',
       'begins', 'behavior', 'beings', 'beliefs', 'believe', 'believed',
       'believes', 'believing', 'beloved', 'ben', 'benaffleck', 'beneath',
       'benfoster', 'beniciodeltoro', 'benjamin', 'benjaminbratt',
       'benkingsley', 'bennett', 'benstiller', 'bent', 'berlin', 'best',
       'bestfriend', 'bet', 'beth', 'betrayal', 'betrayed', 'bettemidler',
       'better', 'betty', 'beverly', 'bible', 'big', 'bigger', 'biggest',
       'biker', 'bikers', 'bikini', 'billhader', 'billionaire',
       'billmurray', 'billnighy', 'billpaxton', 'billpullman', 'billy',
       'billybobthornton', 'billycrudup', 'billycrystal', 'biography',
       'bird', 'birth', 'birthday', 'bisexual', 'bishop', 'bit', 'bite',
       'bitter', 'bizarre', 'black', 'blackmagic', 'blackmail',
       'blackpeople', 'blade', 'blame', 'blind', 'bliss', 'block',
       'blonde', 'blood', 'bloodsplatter', 'bloodthirsty', 'bloody',
       'blow', 'blue', 'board', 'boarding', 'boardingschool', 'boat',
       'bob', 'bobby', 'bobbyfarrelly', 'bobhoskins', 'bodies', 'body',
       'bodyguard', 'bold', 'bollywood', 'bomb', 'bombing', 'bond',
       'bonds', 'bone', 'book', 'books', 'border', 'bored', 'boredom',
       'boring', 'born', 'boss', 'boston', 'botched', 'bound',
       'boundaries', 'bounty', 'bountyhunter', 'bourne', 'box', 'boxer',
       'boxing', 'boy', 'boyfriend', 'boys', 'bradleycooper', 'bradpitt',
       'brain', 'brand', 'brave', 'bravery', 'brazil', 'brazilian',
       'break', 'breakdown', 'breaking', 'breaks', 'brendanfraser',
       'brendangleeson', 'brent', 'brettratner', 'brian', 'briandepalma',
       'bride', 'bridge', 'brief', 'brien', 'bright', 'brilliant',
       'bring', 'bringing', 'brings', 'brink', 'britain', 'british',
       'britishsecretservice', 'brittanymurphy', 'broadway', 'broke',
       'broken', 'broker', 'brooklyn', 'brooks', 'brothel', 'brother',
       'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brought', 'brown', 'bruce',
       'brucewillis', 'brutal', 'brutality', 'brutally', 'bryansinger',
       'buck', 'buddies', 'buddy', 'buddycomedy', 'budget', 'build',
       'building', 'built', 'bully', 'bullying', 'bumbling', 'bunny',
       'burglar', 'buried', 'bus', 'bush', 'business', 'businessman',
       'bust', 'busy', 'butler', 'buy', 'cabin', 'caesar', 'cage',
       'cairo', 'cal', 'california', 'called', 'calls', 'calvin',
       'camcorder', 'came', 'camera', 'cameraman', 'cameras',
       'camerondiaz', 'camp', 'campaign', 'campbell', 'camping', 'campus',
       'canada', 'canadian', 'cancer', 'candidate', 'candy', 'canine',
       'cannibal', 'canuxploitation', 'capable', 'caper', 'capital',
       'capitalism', 'capt', 'captain', 'captive', 'capture', 'captured',
       'captures', 'car', 'caraccident', 'carchase', 'carcrash', 'card',
       'care', 'career', 'carefree', 'cares', 'caretaker',
       'careymulligan', 'caribbean', 'carjourney', 'carl', 'carlagugino',
       'carmen', 'carnival', 'carol', 'carolina', 'carrace', 'carrie',
       'carry', 'carrying', 'cars', 'cartel', 'carter', 'cartoon',
       'caryelwes', 'case', 'caseyaffleck', 'cash', 'casino', 'cast',
       'castle', 'cat', 'cataclysm', 'catastrophe', 'catch', 'catches',
       'cateblanchett', 'catherinekeener', 'catherinezeta', 'catholic',
       'catholicism', 'cattle', 'caught', 'cause', 'caused', 'causes',
       'causing', 'cavalry', 'cave', 'celebrate', 'celebrated',
       'celebration', 'celebrity', 'cellphone', 'cemetery', 'center',
       'centered', 'centers', 'central', 'centuries', 'century',
       'ceremony', 'certain', 'chain', 'chainsaw', 'challenge',
       'challenged', 'challenges', 'champion', 'championship', 'chance',
       'change', 'changed', 'changes', 'changing', 'channingtatum',
       'chaos', 'chaotic', 'chapter', 'character', 'characters', 'charge',
       'charged', 'charismatic', 'charles', 'charlie', 'charliesheen',
       'charlizetheron', 'charlotte', 'charm', 'charming', 'chase',
       'chased', 'chases', 'chauffeur', 'chazzpalminteri', 'cheating',
       'cheerleader', 'chef', 'chemical', 'cher', 'chevychase', 'chicago',
       'chicken', 'chief', 'child', 'childabuse', 'childhero',
       'childhood', 'children', 'chilling', 'china', 'chinese', 'chip',
       'chiwetelejiofor', 'chloëgracemoretz', 'chloësevigny', 'chocolate',
       'choice', 'choices', 'choose', 'chosen', 'chris', 'chriscolumbus',
       'chriscooper', 'chrisevans', 'chrishemsworth', 'chrispine',
       'chrisrock', 'christ', 'christian', 'christianbale',
       'christianity', 'christianslater', 'christinaapplegate',
       'christinaricci', 'christine', 'christmas', 'christmasparty',
       'christopher', 'christopherlloyd', 'christophernolan',
       'christopherplummer', 'christopherwalken', 'christophwaltz',
       'chronicle', 'chronicles', 'chuck', 'church', 'cia',
       'cigarettesmoking', 'cillianmurphy', 'cinema', 'circle', 'circuit',
       'circumstances', 'circus', 'cities', 'citizens', 'city', 'civil',
       'civilization', 'civilwar', 'claim', 'claims', 'claire',
       'clairedanes', 'clan', 'clark', 'clash', 'class', 'classes',
       'classic', 'classmate', 'classmates', 'classroom',
       'claudevandamme', 'clay', 'clean', 'clear', 'clerk', 'client',
       'clients', 'climate', 'climbing', 'clinteastwood', 'cliveowen',
       'clock', 'clone', 'cloning', 'close', 'closer', 'club', 'clubs',
       'clues', 'clutches', 'coach', 'coast', 'cocaine', 'code', 'cody',
       'coffin', 'cohen', 'col', 'cold', 'coldwar', 'cole', 'colin',
       'colinfarrell', 'colinfirth', 'collapse', 'colleague',
       'colleagues', 'collect', 'collection', 'collector', 'college',
       'collide', 'collision', 'colonel', 'colony', 'color', 'colorado',
       'colorful', 'coma', 'combat', 'combined', 'come', 'comeback',
       'comedian', 'comedic', 'comedy', 'comes', 'comet', 'comfort',
       'comic', 'comics', 'coming', 'comingofage', 'comingout', 'command',
       'commander', 'commercial', 'commit', 'commitment', 'committed',
       'common', 'communication', 'community', 'companion', 'company',
       'compete', 'competing', 'competition', 'complete', 'completely',
       'complex', 'complicated', 'complications', 'composer', 'computer',
       'computervirus', 'conan', 'concert', 'conclusion', 'condition',
       'confession', 'confidence', 'confident', 'conflict', 'confront',
       'confronted', 'confused', 'congress', 'conman', 'connected',
       'connection', 'connell', 'connor', 'conquer', 'conscience',
       'consequences', 'conservative', 'considered', 'conspiracy',
       'constant', 'constantly', 'construction', 'contact', 'contain',
       'contemporary', 'contend', 'contest', 'continue', 'continues',
       'continuing', 'contract', 'control', 'controlled', 'controlling',
       'controversial', 'convention', 'converge', 'convict', 'convicted',
       'convince', 'convinced', 'convinces', 'cook', 'cooking', 'cool',
       'cooper', 'cop', 'cope', 'cops', 'core', 'corner', 'corners',
       'corporate', 'corporation', 'corpse', 'corrupt', 'corruption',
       'cost', 'costume', 'couldn', 'count', 'countess', 'countless',
       'countries', 'country', 'countryhouse', 'countrymusic',
       'countryside', 'county', 'coup', 'couple', 'couples', 'courage',
       'courageous', 'course', 'court', 'courtcase', 'courteneycox',
       'courtroom', 'cousin', 'cover', 'covert', 'cow', 'cowardliness',
       'cowboy', 'crab', 'crack', 'craft', 'craig', 'crane', 'crash',
       'crashes', 'crashing', 'crazy', 'create', 'created', 'creates',
       'creation', 'creator', 'creature', 'creatures', 'credit', 'creepy',
       'crew', 'crime', 'crimefighter', 'crimes', 'criminal', 'criminals',
       'crisis', 'critical', 'crocodile', 'crook', 'crooked', 'cross',
       'crossdressing', 'crossed', 'crosses', 'crown', 'crucifixion',
       'cruel', 'cruelty', 'cruise', 'crush', 'crystal', 'cuba',
       'cubagoodingjr', 'cult', 'cultfilm', 'cultural', 'culture',
       'cultureclash', 'cunning', 'cup', 'cure', 'curiosity', 'curious',
       'current', 'curse', 'cursed', 'curtishanson', 'custody',
       'customers', 'cut', 'cuts', 'cuttingthecord', 'cyberpunk',
       'cyborg', 'cynical', 'dad', 'daily', 'dakotafanning', 'dale',
       'damage', 'damon', 'dan', 'danaykroyd', 'dance', 'dancer',
       'dancing', 'danger', 'dangerous', 'dangers', 'daniel',
       'danielcraig', 'danielday', 'danielradcliffe', 'danny',
       'dannyboyle', 'dannydevito', 'dannyglover', 'darcy', 'dare',
       'daring', 'dark', 'darkcomedy', 'darkest', 'darkness',
       'darylhannah', 'dashing', 'date', 'dates', 'dating', 'daughter',
       'daughters', 'dave', 'david', 'davidarquette', 'davidcronenberg',
       'davidduchovny', 'davidfincher', 'davidgordongreen', 'davidmorse',
       'davido', 'davidspade', 'davidthewlis', 'davis', 'daxshepard',
       'day', 'days', 'dc', 'dccomics', 'dea', 'dead', 'deadly', 'deaf',
       'deal', 'dealer', 'dealers', 'dealing', 'deals', 'dean', 'death',
       'deathofafriend', 'deathpenalty', 'deaths', 'debt', 'debut',
       'decade', 'decades', 'decapitation', 'deceased', 'deceit',
       'deception', 'decide', 'decided', 'decides', 'decision',
       'decisions', 'dedicated', 'deeds', 'deep', 'deeper', 'deeply',
       'defeat', 'defend', 'defense', 'deliver', 'delivers', 'delusion',
       'demanding', 'demands', 'demimoore', 'demon', 'demonic',
       'demonicpossession', 'demons', 'dennisdugan', 'dennishopper',
       'dennisquaid', 'dentist', 'denzelwashington', 'department',
       'depressed', 'depression', 'deputy', 'deranged', 'derek',
       'descend', 'desert', 'deserted', 'designed', 'desire', 'desires',
       'desolate', 'despair', 'desperate', 'desperately', 'desperation',
       'despite', 'destined', 'destiny', 'destroy', 'destroyed',
       'destroying', 'destruction', 'details', 'detective', 'detectives',
       'determination', 'determine', 'determined', 'detroit',
       'devastating', 'develop', 'developed', 'develops', 'device',
       'devil', 'devoted', 'diabolical', 'dialogue', 'diamond', 'diane',
       'dianekeaton', 'dianekruger', 'dianelane', 'diary', 'dick',
       'dictator', 'did', 'didn', 'die', 'died', 'diego', 'dies',
       'differences', 'different', 'difficult', 'digging', 'dignity',
       'diner', 'dinner', 'dinosaur', 'dinosaurs', 'dire', 'directed',
       'direction', 'director', 'dirt', 'dirty', 'dirtycop', 'disabled',
       'disappearance', 'disappeared', 'disappears', 'disaster',
       'disastrous', 'discover', 'discovered', 'discovering', 'discovers',
       'discovery', 'disease', 'disfigurement', 'disgraced', 'disguise',
       'dishonesty', 'disillusioned', 'disney', 'disorder', 'dispatched',
       'distant', 'district', 'distrust', 'disturbed', 'disturbing',
       'diva', 'divided', 'division', 'divorce', 'divorced', 'dna', 'doc',
       'doctor', 'document', 'documentary', 'documents', 'does', 'doesn',
       'dog', 'dogs', 'doing', 'doll', 'dollar', 'dollars', 'dolphin',
       'domination', 'don', 'donaldpetrie', 'donaldsutherland',
       'doncheadle', 'donnell', 'doomed', 'door', 'dorothy', 'double',
       'doublelife', 'doubt', 'doubts', 'doug', 'douglas', 'dr',
       'dracula', 'drag', 'dragon', 'drama', 'dramatic', 'draw',
       'drawing', 'drawn', 'draws', 'dream', 'dreams', 'drew',
       'drewbarrymore', 'drifter', 'drink', 'drinking', 'drive', 'driven',
       'driver', 'drives', 'driving', 'drop', 'drowning', 'drug',
       'drugabuse', 'drugaddiction', 'drugdealer', 'druglord', 'drugs',
       'drugtraffic', 'drunk', 'drunken', 'du', 'dualidentity', 'dude',
       'duel', 'duke', 'dumped', 'duo', 'duringcreditsstinger',
       'dustinhoffman', 'dutch', 'duty', 'dwarves', 'dwaynejohnson',
       'dying', 'dyinganddeath', 'dylan', 'dynamic', 'dynasty',
       'dysfunctional', 'dysfunctionalfamily', 'dystopia',
       'dystopicfuture', 'eager', 'earlier', 'early', 'earn', 'earth',
       'earthquake', 'east', 'easy', 'eating', 'eccentric', 'economic',
       'economics', 'economy', 'eddie', 'eddiegriffin', 'eddiemurphy',
       'edgar', 'edge', 'edharris', 'editor', 'education', 'edward',
       'edwardburns', 'edwardnorton', 'edwardzwick', 'effort', 'efforts',
       'egg', 'ego', 'egypt', 'egyptian', 'el', 'elaborate', 'elderly',
       'election', 'elements', 'elephant', 'eliaskoteas', 'elijahwood',
       'eliminate', 'elisabethshue', 'elite', 'elizabeth',
       'elizabethbanks', 'ella', 'ellenburstyn', 'ellenpage', 'ellie',
       'elliot', 'ellis', 'elusive', 'elves', 'elvis', 'embark',
       'embarking', 'embarks', 'embassy', 'embroiled', 'emerge',
       'emergency', 'emerges', 'emilehirsch', 'emily', 'emilyblunt',
       'emilymortimer', 'emilywatson', 'emma', 'emmastone',
       'emmathompson', 'emmawatson', 'emotional', 'emotionally',
       'emotions', 'emperor', 'empire', 'employee', 'employees',
       'employer', 'employs', 'encounter', 'encounters', 'end', 'ended',
       'ending', 'endless', 'endoftheworld', 'ends', 'enemies', 'enemy',
       'energy', 'enforcement', 'engaged', 'engagement', 'engineer',
       'england', 'english', 'enigmatic', 'enjoy', 'enlist', 'enlists',
       'enormous', 'ensemblecast', 'ensues', 'entangled', 'enter',
       'enterprise', 'enters', 'entertainer', 'entertaining', 'entire',
       'entirely', 'entity', 'environment', 'environmental', 'epic',
       'epidemic', 'era', 'eric', 'ericbana', 'erin', 'ernest',
       'eroticism', 'erupts', 'escapade', 'escape', 'escaped', 'escapes',
       'escaping', 'escort', 'especially', 'espionage', 'establishment',
       'estate', 'estranged', 'eternal', 'ethan', 'ethanhawke',
       'eugenelevy', 'europe', 'european', 'eva', 'evacuation', 'evade',
       'evamendes', 'evanrachelwood', 'eve', 'evening', 'event', 'events',
       'eventually', 'everybody', 'everyday', 'evidence', 'evil',
       'evolution', 'ewanmcgregor', 'ex', 'exact', 'exactly', 'examines',
       'exchange', 'exciting', 'exclusive', 'execution', 'executive',
       'exercise', 'exist', 'existed', 'existence', 'existentialism',
       'exists', 'exorcism', 'exotic', 'exoticisland', 'expectations',

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

In [ ]:
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()

In [ ]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [ ]:
stem("loving")

'love'

In [ ]:
stem("in  the  22nd  century,  a  paraplegic  marine  is  dispatched  to  the  moon  pandora  on  a  unique  mission,  but  becomes  torn  between  following  orders  and  protecting  an  alien  civilization.  action  adventure  fantasy  sciencefiction  cultureclash  future  spacewar  spacecolony  society  spacetravel  futuristic  romance  space  alien  tribe  alienplanet  cgi  marine  soldier  battle  loveaffair  antiwar  powerrelations  mindandsoul  3d  samworthington  zoesaldana  sigourneyweaver  jamescameron")

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [ ]:
newdf["tags"]=newdf["tags"].apply(stem)

<ipython-input-60-3fc93b68419b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf["tags"]=newdf["tags"].apply(stem)

In [ ]:
newdf["tags"]

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
tags                                                  nan
Name: tags, Length: 4807, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words="english")

vectors=cv.fit_transform(newdf['tags']).toarray()

In [ ]:
vectors

KeyboardInterrupt:

In [ ]:
cv.get_feature_names_out()

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '18', '18th', '18thcenturi', '19', '1910', '1920', '1930',
       '1940', '1944', '1950', '1950s', '1960', '1960s', '1970', '1970s',
       '1971', '1974', '1976', '1980', '1985', '1990', '1999', '19th',
       '19thcenturi', '20', '200', '2003', '2009', '20th', '21st', '23',
       '24', '25', '30', '300', '3d', '40', '50', '500', '60', '70', '80',
       'aaron', 'aaroneckhart', 'abandon', 'abduct', 'abigailbreslin',
       'abil', 'abl', 'aboard', 'abov', 'abus', 'academ', 'academi',
       'accept', 'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'account', 'accus', 'ace', 'achiev', 'acquaint',
       'act', 'action', 'actionhero', 'activ', 'activist', 'activities',
       'actor', 'actress', 'actual', 'ad', 'adam', 'adamsandl',
       'adamshankman', 'adapt', 'add', 'addict', 'adjust', 'admir',
       'admit', 'adolesc', 'adopt', 'ador', 'adrienbrodi', 'adult',
       'adultanim', 'adulteri', 'adulthood', 'advanc', 'adventur',
       'adventure', 'adventures', 'advertis', 'advic', 'advis', 'affair',
       'affect', 'afghanistan', 'africa', 'african', 'africanamerican',
       'aftercreditssting', 'afterlif', 'aftermath', 'ag', 'age',
       'agediffer', 'agenc', 'agency', 'agenda', 'agent', 'agents',
       'aggress', 'ago', 'agre', 'ahead', 'aid', 'aidanquinn', 'ail',
       'aim', 'air', 'airplan', 'airplanecrash', 'airport', 'aka', 'al',
       'alabama', 'alan', 'alaska', 'albert', 'alcatraz', 'alcohol',
       'alecbaldwin', 'alex', 'alexkendrick', 'alfredhitchcock',
       'alfredmolina', 'ali', 'alic', 'alice', 'alien', 'alieninvas',
       'alienlife', 'alienplanet', 'alik', 'aliv', 'alive', 'allen',
       'alli', 'allianc', 'allow', 'alon', 'alongsid', 'alpacino',
       'alpha', 'alreadi', 'alter', 'altern', 'alway', 'alyssa',
       'alzheimer', 'amanda', 'amandapeet', 'amandaseyfri', 'amateur',
       'amaz', 'amazon', 'ambassador', 'ambit', 'ambiti', 'ambul',
       'ambush', 'america', 'american', 'americanabroad',
       'americancivilwar', 'americanfootbal', 'americanfootballplay',
       'amid', 'amidst', 'amnesia', 'amp', 'amsterdam', 'amus',
       'amusementpark', 'amy', 'amyadam', 'amysmart', 'ana', 'anakin',
       'analyst', 'anarchiccomedi', 'ancient', 'ancientrom',
       'ancientworld', 'anderson', 'andi', 'andiemacdowel', 'andrew',
       'android', 'andy', 'andygarcía', 'angel', 'angela',
       'angelabassett', 'angeles', 'angelinajoli', 'anger', 'angle',
       'angri', 'ani', 'anim', 'animalattack', 'animalhorror', 'animals',
       'anjelicahuston', 'ann', 'anna', 'annafari', 'annakendrick',
       'anne', 'annehathaway', 'annemoss', 'annetteben', 'anni', 'annie',
       'anniversari', 'announc', 'annual', 'anonym', 'anoth', 'answer',
       'ant', 'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin',
       'anthonymacki', 'anthropomorph', 'anti', 'antic', 'antihero',
       'antiqu', 'antoinefuqua', 'antoniobandera', 'antonyelchin',
       'anyon', 'anyth', 'apart', 'apartheid', 'apartment', 'ape',
       'apocalyps', 'apocalypse', 'apocalypt', 'appar', 'appear', 'appl',
       'apple', 'appoint', 'appreci', 'apprentic', 'approach', 'april',
       'aquarium', 'arab', 'arch', 'archaeologist', 'archeolog', 'archer',
       'architect', 'arctic', 'area', 'aren', 'arena', 'argument', 'aris',
       'aristocrat', 'arm', 'armi', 'armor', 'armsdeal', 'army', 'arnold',
       'arnoldschwarzenegg', 'arrang', 'arrangedmarriag', 'arrest',
       'arriv', 'arrog', 'art', 'arthur', 'artifact', 'artifici',
       'artificialintellig', 'artist', 'ash', 'ashley', 'ashleyjudd',
       'ashtonkutch', 'asia', 'asian', 'asid', 'ask', 'aspect', 'aspir',
       'assassin', 'assault', 'assembl', 'assign', 'assist', 'assistant',
       'associ', 'assum', 'asteroid', 'astronaut', 'asylum', 'atheist',
       'athlet', 'atom', 'atomicbomb', 'attack', 'attacks', 'attempt',
       'attempttoescap', 'attend', 'attent', 'attic', 'attitud',
       'attorney', 'attract', 'auction', 'audienc', 'audit', 'august',
       'aunt', 'austin', 'australia', 'australian', 'author', 'autism',
       'auto', 'automobilerac', 'aveng', 'averag', 'avoid', 'await',
       'awak', 'awaken', 'awar', 'award', 'away', 'awkward', 'awri',
       'awry', 'ax', 'babe', 'babi', 'baby', 'bachelor', 'backdrop',
       'background', 'backpack', 'bad', 'bag', 'bahama', 'bail', 'balanc',
       'ball', 'ballet', 'balloon', 'baltimor', 'ban', 'band', 'bandit',
       'bangkok', 'banish', 'bank', 'banker', 'bankrobb', 'bankrobberi',
       'bar', 'barbrastreisand', 'bare', 'bargain', 'barn', 'barney',
       'baron', 'barri', 'barrylevinson', 'barrysonnenfeld', 'bas',
       'base', 'basebal', 'basedoncomicbook', 'basedongraphicnovel',
       'basedonnovel', 'basedonplay', 'basedonstagemus', 'basedontrueev',
       'basedontruestori', 'basedontvseri', 'basedonvideogam',
       'basedonyoungadultnovel', 'basement', 'basketbal', 'basketball',
       'bat', 'batman', 'battl', 'battle', 'battlefield', 'bay', 'beach',
       'beam', 'bear', 'beard', 'beast', 'beat', 'beauti', 'beautiful',
       'beautifulwoman', 'beauty', 'becam', 'becaus', 'becki', 'becom',
       'becominganadult', 'bed', 'bedroom', 'bee', 'beer', 'befor',
       'befriend', 'began', 'begin', 'begins', 'behavior', 'belief',
       'believ', 'bell', 'bella', 'belong', 'belov', 'ben', 'benaffleck',
       'bend', 'beneath', 'benefit', 'benfost', 'beniciodeltoro',
       'benjamin', 'benjaminbratt', 'benkingsley', 'bennett', 'benstil',
       'bent', 'berlin', 'best', 'bestfriend', 'bestfriendsinlov', 'bet',
       'beth', 'betray', 'bettemidl', 'better', 'betti', 'beverli',
       'bibl', 'bid', 'big', 'bigger', 'biggest', 'bike', 'biker',
       'bikini', 'billhad', 'billi', 'billionair', 'billmurray',
       'billnighi', 'billpaxton', 'billpullman', 'billybobthornton',
       'billycrudup', 'billycryst', 'biographi', 'biolog', 'bird',
       'birth', 'birthday', 'bisexu', 'bishop', 'bit', 'bite', 'bitter',
       'bizarr', 'black', 'blackmag', 'blackmail', 'blackpeopl',
       'blacksmith', 'blade', 'blame', 'blend', 'blind', 'bliss',
       'blizzard', 'block', 'blond', 'blood', 'bloodi', 'bloodsplatt',
       'bloodthirsti', 'blow', 'blue', 'board', 'boardingschool', 'boat',
       'bob', 'bobbi', 'bobbyfarrelli', 'bobhoskin', 'bodi', 'body',
       'bodyguard', 'bold', 'bollywood', 'bomb', 'bond', 'bone', 'book',
       'border', 'bore', 'boredom', 'born', 'boss', 'boston', 'botch',
       'bound', 'boundari', 'bounti', 'bountyhunt', 'bout', 'box',
       'boxer', 'boy', 'boyfriend', 'boys', 'bradleycoop', 'bradpitt',
       'brain', 'brainwash', 'brand', 'brandon', 'brave', 'braveri',
       'brazil', 'brazilian', 'break', 'breakdown', 'breakup', 'breast',
       'breath', 'breed', 'brendanfras', 'brendangleeson', 'brent',
       'brettratn', 'brian', 'briandepalma', 'bride', 'bridesmaid',
       'bridg', 'brief', 'brielarson', 'brien', 'bright', 'brilliant',
       'bring', 'brink', 'britain', 'british', 'britishsecretservic',
       'brittanymurphi', 'broadcast', 'broadway', 'broke', 'broken',
       'broker', 'bronx', 'brook', 'brooklyn', 'broom', 'brothel',
       'brother', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brought', 'brown', 'bruce',
       'brucegreenwood', 'brucewilli', 'brutal', 'bryansing', 'bu',
       'buck', 'bud', 'buddi', 'buddy', 'buddycomedi', 'buddycop',
       'budget', 'build', 'building', 'built', 'bullet', 'bulli', 'bumbl',
       'bunch', 'bunker', 'bunni', 'burglar', 'buri', 'burn', 'bush',
       'busi', 'business', 'businessman', 'bust', 'butcher', 'butler',
       'butt', 'button', 'buy', 'buzz', 'cabin', 'caesar', 'cage',
       'cairo', 'cal', 'california', 'calvin', 'camcord', 'came',
       'camera', 'cameraman', 'camerondiaz', 'camp', 'campaign',
       'campbell', 'campu', 'canada', 'canadian', 'cancer', 'candi',
       'candid', 'canin', 'cannib', 'canuxploit', 'capabl', 'caper',
       'capit', 'capt', 'captain', 'captiv', 'captur', 'capture', 'car',
       'caraccid', 'carchas', 'carcrash', 'card', 'care', 'career',
       'carefre', 'caretak', 'careymulligan', 'caribbean', 'carjourney',
       'carl', 'carlagugino', 'carmen', 'carol', 'carolina', 'carrac',
       'carri', 'carrie', 'cartel', 'carter', 'cartoon', 'caryelw',
       'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castl', 'cat',
       'cataclysm', 'catastroph', 'catch', 'cateblanchett',
       'catherinedeneuv', 'catherinekeen', 'catherinezeta', 'cathol',
       'catholic', 'cattl', 'caught', 'caus', 'cavalri', 'cave',
       'cavemen', 'celebr', 'celebration', 'cell', 'cellphon', 'cemeteri',
       'center', 'centr', 'central', 'centuri', 'centuries', 'century',
       'ceo', 'certain', 'chad', 'chain', 'chainsaw', 'challeng',
       'chamber', 'champion', 'championship', 'chanc', 'chance', 'chang',
       'change', 'changed', 'changes', 'channingtatum', 'chao', 'chaos',
       'chaotic', 'chapter', 'charact', 'character', 'characters',
       'charg', 'charismat', 'charl', 'charli', 'charlie', 'charliesheen',
       'charlizetheron', 'charm', 'chart', 'chase', 'chauffeur',
       'chazzpalminteri', 'cheat', 'check', 'cheerlead', 'chef', 'chemic',
       'cher', 'chevychas', 'chicago', 'chicken', 'chief', 'child',
       'childabus', 'childhero', 'childhood', 'childprodigi', 'children',
       'chill', 'chimp', 'china', 'chines', 'chip', 'chipmunk',
       'chiwetelejiofor', 'chloe', 'chloëgracemoretz', 'chloësevigni',
       'chocol', 'choic', 'choice', 'choos', 'chosen', 'chowyun', 'chri',
       'chriscolumbu', 'chriscoop', 'chrisevan', 'chrishemsworth',
       'chrisklein', 'chrispin', 'chrisrock', 'christ', 'christian',
       'christianbal', 'christianslat', 'christin', 'christinaappleg',
       'christinaricci', 'christma', 'christmas', 'christmasparti',
       'christmastre', 'christoph', 'christopherlambert',
       'christopherlloyd', 'christophernolan', 'christopherplumm',
       'christopherwalken', 'christophwaltz', 'chrisweitz', 'chronicl',
       'chuck', 'church', 'cia', 'ciaránhind', 'cigarettesmok',
       'cillianmurphi', 'cinema', 'circl', 'circu', 'circuit', 'circumst',
       'citi', 'citizen', 'city', 'civil', 'civilian', 'civilwar',
       'claim', 'clair', 'clairedan', 'claireforlani', 'clan', 'clark',
       'clash', 'class', 'classdiffer', 'classic', 'classmat',
       'classroom', 'claudevandamm', 'clay', 'clean', 'clear', 'clerk',
       'clever', 'client', 'clients', 'cliff', 'climat', 'climb',
       'clinteastwood', 'cliveowen', 'clock', 'clone', 'close', 'closer',
       'cloud', 'clown', 'club', 'clue', 'clueless', 'clutch', 'coach',
       'coast', 'cocain', 'code', 'coffin', 'cohen', 'col', 'cold',
       'coldwar', 'cole', 'colin', 'colinfarrel', 'colinfirth', 'collaps',
       'colleagu', 'collect', 'collector', 'colleg', 'college', 'collid',
       'collis', 'colombia', 'colonel', 'coloni', 'color', 'colorado',
       'coma', 'combat', 'combin', 'come', 'comeback', 'comed', 'comedi',
       'comedian', 'comedy', 'comet', 'comfort', 'comic', 'coming',
       'comingofag', 'comingout', 'command', 'commando', 'commerci',
       'commiss', 'commit', 'common', 'commun', 'communist', 'community',
       'compani', 'companion', 'company', 'compet', 'competit',
       'competition', 'complet', 'complex', 'complic', 'compos',
       'compuls', 'comput', 'computerviru', 'conan', 'concern', 'concert',
       'concoct', 'condit', 'condition', 'conduct', 'confeder', 'confess',
       'confid', 'confin', 'conflict', 'confront', 'confus', 'congress',
       'conman', 'connect', 'connecticut', 'connel', 'connor', 'conquer',
       'consequ', 'consequences', 'conserv', 'consid', 'conspir',
       'conspiraci', 'conspiracy', 'constant', 'constantli', 'construct',
       'consum', 'contact', 'contain', 'contemporari', 'contend',
       'content', 'contest', 'continu', 'contract', 'contractor',
       'control', 'controversi', 'convent', 'converg', 'convers',
       'convict', 'convinc', 'cook', 'cool', 'cooper', 'cop', 'cope',
       'cops', 'core', 'corner', 'corp', 'corpor', 'corporation', 'corps',
       'corrupt', 'cost', 'costum', 'couldn', 'counselor', 'count',
       'countess', 'countless', 'countri', 'country', 'countryhous',
       'countrymus', 'countrysid', 'coup', 'coupl', 'couple', 'courag',
       'cours', 'court', 'courtcas', 'courteneycox', 'courtroom',
       'cousin', 'cover', 'covert', 'covet', 'cow', 'cowardli', 'cowboy',
       'crab', 'crack', 'craft', 'craig', 'crane', 'crash', 'crave',
       'crazi', 'creat', 'creation', 'creativ', 'creator', 'creatur',
       'creature', 'creatures', 'credit', 'creepi', 'crew', 'cri',
       'crime', 'crimefight', 'crimes', 'crimin', 'criminal', 'criminals',
       'crisi', 'crisis', 'critic', 'crocodil', 'crook', 'cross',
       'crossdress', 'crowd', 'crown', 'crucifixion', 'cruel', 'cruelti',
       'cruis', 'crusad', 'crush', 'crystal', 'cuba', 'cubagoodingjr',
       'culmin', 'cult', 'cultfilm', 'cultur', 'culture', 'cultureclash',
       'cun', 'cup', 'cure', 'current', 'curs', 'curse', 'curtishanson',
       'custodi', 'custom', 'cut', 'cuttingthecord', 'cyberpunk',
       'cyborg', 'cynic', 'dad', 'daili', 'dakotafan', 'dale', 'damag',
       'damon', 'dan', 'danaykroyd', 'danc', 'dancer', 'danger', 'daniel',
       'danielcraig', 'danielday', 'danielradcliff', 'danni', 'danny',
       'dannyboyl', 'dannydevito', 'dannyglov', 'dare', 'dark',
       'darkcomedi', 'darkest', 'darkness', 'darylhannah', 'dash', 'date',
       'daughter', 'daughters', 'dave', 'davi', 'david', 'davidarquett',
       'davidcronenberg', 'davidduchovni', 'davidfinch',
       'davidgordongreen', 'davidmors', 'davido', 'davidschwimm',
       'davidspad', 'davidthewli', 'dawn', 'daxshepard', 'day',
       'daydream', 'days', 'dc', 'dccomic', 'dea', 'dead', 'deadli',
       'deadliest', 'deaf', 'deal', 'dealer', 'dean', 'death',
       'deathofafriend', 'deathoffath', 'deathpenalti', 'debt', 'debut',
       'decad', 'decapit', 'deceas', 'deceit', 'decept', 'decid', 'decis',
       'declar', 'dedic', 'deed', 'deep', 'deeper', 'deepli', 'defeat',
       'defend', 'defens', 'defi', 'defin', 'delight', 'deliv',
       'deliveri', 'delus', 'demand', 'demimoor', 'demon',
       'demonicpossess', 'demons', 'deni', 'deniserichard', 'denmark',
       'denni', 'dennisdugan', 'dennishopp', 'dennisquaid', 'dentist',
       'denzelwashington', 'depart', 'depend', 'depict', 'depress',
       'depth', 'deputi', 'derang', 'derek', 'derekluk', 'descend',
       'describ', 'desert', 'design', 'desir', 'desk', 'desol', 'despair',
       'desper', 'despit', 'destin', 'destini', 'destiny', 'destroy',
       'destroyed', 'destruct', 'destruction', 'detect', 'detective',
       'determin', 'detroit', 'devast', 'develop', 'devic', 'devil',
       'deviou', 'devis', 'devot', 'diabol', 'diagnos', 'dialogu',
       'diamond', 'dian', 'dianekeaton', 'dianekrug', 'dianelan', 'diari',
       'dick', 'dictat', 'did', 'didn', 'die', 'died', 'diego', 'dies',
       'differ', 'different', 'difficult', 'difficulti', 'dig', 'dilemma',
       'diner', 'dinner', 'dinosaur', 'diplomat', 'dire', 'direct',
       'director', 'dirt', 'dirti', 'dirtycop', 'disabl', 'disappear',
       'disappears', 'disast', 'disaster', 'disastr', 'discov',
       'discoveri', 'diseas', 'disease', 'disfigur', 'disgrac', 'disguis',
       'dishonesti', 'disillus', 'disney', 'disord', 'dispatch',
       'disrupt', 'distant', 'district', 'distrust', 'disturb', 'ditch',
       'diva', 'dive', 'divid', 'divis', 'divorc', 'divorce', 'dj', 'dna',
       'doc', 'doctor', 'document', 'documentari', 'dodg', 'doe', 'doesn',
       'dog', 'doll', 'dollar', 'dolphin', 'dolphlundgren', 'domest',
       'domin', 'don', 'donaldpetri', 'donaldsutherland', 'doncheadl',
       'donnel', 'doom', 'doomsday', 'door', 'doorstep', 'doppelgang',
       'dorothi', 'doubl', 'double', 'doublecross', 'doublelif', 'doubt',
       'doug', 'dougliman', 'dr', 'dracula', 'drag', 'dragon', 'drama',
       'dramat', 'draw', 'drawn', 'dread', 'dream', 'dreams', 'dress',
       'drew', 'drewbarrymor', 'drift', 'drifter', 'drink', 'drive',
       'driven', 'driver', 'drone', 'drop', 'drown', 'drug', 'drugabus',
       'drugaddict', 'drugdeal', 'druglord', 'drugs', 'drugsmuggl',
       'drugtraff', 'drugus', 'drunk', 'drunken', 'du', 'dualident',
       'dub', 'duck', 'dude', 'duel', 'duke', 'dump', 'duo', 'dure',
       'duringcreditssting', 'dustinhoffman', 'dutch', 'duti', 'dwarv',
       'dwaynejohnson', 'dyinganddeath', 'dylan', 'dynam', 'dynasti',
       'dysfunct', 'dysfunctionalfamili', 'dystopia', 'dystopicfutur',
       'eager', 'earli', 'earlier', 'earn', 'earth', 'earthquak', 'easi',
       'easili', 'east', 'eat', 'eccentr', 'econom', 'economi', 'eddi',
       'eddiegriffin', 'eddiemurphi', 'edg', 'edgar', 'edharri', 'editor',
       'educ', 'edward', 'edwardburn', 'edwardnorton', 'edwardzwick',
       'effect', 'effort', 'egg', 'ego', 'egypt', 'egyptian', 'el',
       'elabor', 'elderli', 'elect', 'element', 'eleph', 'elev',
       'eliaskotea', 'elijahwood', 'elimin', 'elisabethshu', 'elit',
       'elite', 'elizabeth', 'elizabethbank', 'ella', 'ellenburstyn',
       'ellenpag', 'elli', 'elliot', 'elliott', 'els', 'elud', 'elus',
       'elv', 'elvi', 'embark', 'embassi', 'embroil', 'emerg', 'emigr',
       'emilehirsch', 'emili', 'emilyblunt', 'emilymortim', 'emilywatson',
       'emma', 'emmarobert', 'emmaston', 'emmathompson', 'emmawatson',
       'emot', 'emperor', 'empir', 'empire', 'employ', 'employe',
       'employer', 'enabl', 'enchant', 'encount', 'encourag', 'end',
       'endless', 'endoftheworld', 'endur', 'enemi', 'enemies', 'enemy',
       'energi', 'enforc', 'engag', 'engin', 'england', 'english',
       'enigmat', 'enjoy', 'enlist', 'enorm', 'enrol', 'ensemblecast',
       'ensu', 'ensues', 'ensur', 'entangl', 'enter', 'enterpris',
       'entertain', 'enthusiast', 'entir', 'entiti', 'environ',
       'environment', 'epic', 'epidem', 'episod', 'equal', 'era', 'eric',
       'ericbana', 'erin', 'ernest', 'erotic', 'erupt', 'escap',
       'escapad', 'escape', 'escapefromprison', 'escort', 'especi',
       'espionag', 'establish', 'estat', 'estrang', 'etern', 'ethan',
       'ethanhawk', 'ethic', 'eugenelevi', 'europ', 'european', 'eva',
       'evacu', 'evad', 'evamend', 'evanrachelwood', 'eve', 'event',
       'events', 'eventu', 'eventually', 'everi', 'everybodi', 'everyday',
       'everyon', 'everyth', 'evid', 'evil', 'evolut', 'evolv',
       'ewanmcgregor', 'ex', 'exact', 'exactli', 'exam', 'examin',
       'exchang', 'excit', 'exclus', 'execut', 'exercis', 'exhibit',
       'exil', 'exist', 'existence', 'existenti', 'exorc', 'exot',
       'exoticisland', 'expect', 'expected', 'expedit', 'experi',
       'experienc', 'experience', 'experiment', 'expert', 'explain',
       'explod', 'exploit', 'explor', 'explos', 'expos', 'extend',
       'extra', 'extramaritalaffair', 'extraordinari', 'extraterrestri',
       'extraterrestrialtechnolog', 'extrem', 'extremeviol', 'eye',
       'eyes', 'fabl', 'fac', 'face', 'facil', 'fact', 'faction',
       'factori', 'fade', 'fail', 'fairi', 'fairytal', 'faith', 'fake',
       'falcon', 'fall', 'fallen', 'fallinginlov', 'fals', 'falseident',
       'falselyaccus', 'fame', 'famili', 'families', 'family',
       'familyconflict', 'familyrelationship', 'famkejanssen', 'famou',
       'famous', 'fan', 'fanat', 'fangvamp', 'fans', 'fantasi', 'fantast',
       'fantasyworld', 'far', 'farewel', 'farm', 'farmer', 'fascin',
       'fashion', 'fast', 'faster', 'fat', 'fatal', 'fate', 'father',
       'fatherdaughterrelationship', 'fathersonrelationship', 'favor',
       'favorit', 'fbi', 'fbiagent', 'fear', 'fearless', 'fearsom',

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors)

In [ ]:
similarity.shape

(4807, 4807)

In [ ]:
similarity[3]

array([0.07347184, 0.03883678, 0.06004806, 1.        , 0.03303192,
       0.06052275, 0.05617667, 0.06827887, 0.04134491, 0.20483662,
       0.08951436, 0.06606383, 0.02102586, 0.01570186, 0.07252377,
       0.0438529 , 0.03673592, 0.01393737, 0.04003204, 0.02923527,
       0.03050444, 0.05741693, 0.02360961, 0.        , 0.0930726 ,
       0.08354674, 0.07161149, 0.02899464, 0.06100889, 0.09078413,
       0.09331813, 0.13323468, 0.02973505, 0.04529108, 0.        ,
       0.04622502, 0.06827887, 0.01836796, 0.09907424, 0.05741693,
       0.01790287, 0.09909575, 0.        , 0.0634202 , 0.02360961,
       0.07189966, 0.01941839, 0.08238526, 0.01474099, 0.0203363 ,
       0.05913124, 0.0418121 , 0.01706972, 0.07498688, 0.        ,
       0.01228127, 0.09656091, 0.08439495, 0.109913  , 0.03797773,
       0.03846154, 0.02311251, 0.02923527, 0.01426535, 0.02067246,
       0.42256142, 0.03140371, 0.03774257, 0.04205171, 0.02773501,
       0.0176832 , 0.03413944, 0.11483385, 0.02311251, 0.04710557,
       0.01813094, 0.08347257, 0.04018934, 0.0176832 , 0.05798929,
       0.0352235 , 0.05128205, 0.08841598, 0.01570186, 0.0431398 ,
       0.06827887, 0.        , 0.03883678, 0.02102586, 0.04018934,
       0.        , 0.05913124, 0.01449732, 0.06606383, 0.06537205,
       0.04902903, 0.07161149, 0.06470154, 0.0176832 , 0.07445808,
       0.07082882, 0.07161149, 0.04349197, 0.05574947, 0.05825517,
       0.02414023, 0.01449732, 0.02875987, 0.08439495, 0.        ,
       0.        , 0.01747141, 0.03580574, 0.04539206, 0.01601282,
       0.06107048, 0.1168616 , 0.        , 0.        , 0.31774445,
       0.03268602, 0.03883678, 0.08134518, 0.06280743, 0.01570186,
       0.07299319, 0.03722904, 0.06369556, 0.05661385, 0.04852616,
       0.05661385, 0.03673592, 0.03140371, 0.        , 0.06793662,
       0.04279605, 0.04902903, 0.05256464, 0.03580574, 0.14044168,
       0.09421114, 0.        , 0.        , 0.03026138, 0.01747141,
       0.04031297, 0.03396831, 0.09709195, 0.04529108, 0.0270666 ,
       0.07643467, 0.02360961, 0.01941839, 0.12357788, 0.04279605,
       0.0570614 , 0.0418121 , 0.09245003, 0.04665906, 0.04441156,
       0.10510691, 0.        , 0.02311251, 0.08951436, 0.0930726 ,
       0.04803845, 0.08735707, 0.08410343, 0.06988566, 0.06163336,
       0.11894021, 0.0317101 , 0.07412493, 0.03235077, 0.05439283,
       0.        , 0.04067259, 0.        , 0.05120916, 0.02531848,
       0.09245003, 0.        , 0.08171506, 0.03684381, 0.01747141,
       0.03536639, 0.0549235 , 0.01790287, 0.09245003, 0.1067521 ,
       0.02948198, 0.03413944, 0.06606383, 0.06598588, 0.02264554,
       0.02067246, 0.07252377, 0.03871048, 0.08006408, 0.01526762,
       0.02531848, 0.04622502, 0.        , 0.07767356, 0.08633531,
       0.12988108, 0.01290349, 0.03580574, 0.04279605, 0.14165765,
       0.29701404, 0.        , 0.15408339, 0.08238526, 0.03827795,
       0.09245003, 0.04529108, 0.0594701 , 0.05337605, 0.0855921 ,
       0.02067246, 0.        , 0.05574947, 0.03626189, 0.12738117,
       0.04902903, 0.02102586, 0.01913898, 0.04622502, 0.07502345,
       0.06410256, 0.        , 0.03883678, 0.02414023, 0.04499213,
       0.        , 0.08006408, 0.04622502, 0.19355242, 0.02547822,
       0.03268602, 0.03673592, 0.07548514, 0.01617539, 0.06419407,
       0.05661385, 0.0662615 , 0.06307757, 0.09331813, 0.02414023,
       0.02220578, 0.        , 0.09907424, 0.0438529 , 0.        ,
       0.01747141, 0.07792865, 0.03722904, 0.03706247, 0.0855921 ,
       0.0203363 , 0.06751596, 0.0594701 , 0.02264554, 0.0418121 ,
       0.        , 0.06906825, 0.06793662, 0.        , 0.02067246,
       0.03081668, 0.03303192, 0.03883678, 0.07370496, 0.05370862,
       0.12009612, 0.02179068, 0.07412493, 0.03268602, 0.08087693,
       0.07252377, 0.12104551, 0.10887115, 0.17225078, 0.01282051,
       0.0954171 , 0.17720318, 0.01813094, 0.05741693, 0.01601282,
       0.04358136, 0.05180119, 0.02067246, 0.        , 0.        ,
       0.05510388, 0.08119979, 0.04622502, 0.06677806, 0.31815821,
       0.05120916, 0.05229764, 0.01634301, 0.09709195, 0.07347184,
       0.        , 0.        , 0.09760722, 0.09443843, 0.        ,
       0.05349506, 0.05241424, 0.08735707, 0.        , 0.15130688,
       0.07767356, 0.06916483, 0.05063697, 0.        , 0.02311251,
       0.02139802, 0.02470831, 0.05510388, 0.04134491, 0.05063697,
       0.04622502, 0.01971041, 0.03774257, 0.        , 0.03673592,
       0.01747141, 0.06280743, 0.03722904, 0.06827887, 0.05063697,
       0.06470154, 0.        , 0.0317101 , 0.        , 0.10241831,
       0.01726706, 0.01913898, 0.12503908, 0.01343766, 0.04134491,
       0.08087693, 0.05741693, 0.        , 0.02139802, 0.0176832 ,
       0.06827887, 0.1268404 , 0.        , 0.01437993, 0.10591482,
       0.1019129 , 0.10512928, 0.0549235 , 0.02102586, 0.08716273,
       0.02923527, 0.03494283, 0.04441156, 0.01383297, 0.03268602,
       0.05241424, 0.03942083, 0.07082882, 0.        , 0.10609918,
       0.15914877, 0.03338903, 0.08257979, 0.        , 0.        ,
       0.0285307 , 0.08171506, 0.1132277 , 0.04279605, 0.04721922,
       0.03626189, 0.02923527, 0.02668803, 0.06052275, 0.02001602,
       0.        , 0.04580286, 0.11561171, 0.04803845, 0.06100889,
       0.        , 0.03948736, 0.06307757, 0.01861452, 0.05180119,
       0.        , 0.09160572, 0.05439283, 0.06163336, 0.01651596,
       0.06307757, 0.        , 0.05439283, 0.04349197, 0.04358136,
       0.09709195, 0.01449732, 0.04460258, 0.13587324, 0.03268602,
       0.01706972, 0.03673592, 0.05008354, 0.01971041, 0.04134491,
       0.07457013, 0.0176832 , 0.02311251, 0.        , 0.01601282,
       0.03140371, 0.1132277 , 0.0203363 , 0.01437993, 0.03871048,
       0.14867526, 0.03751172, 0.01836796, 0.32470271, 0.01887128,
       0.0176832 , 0.        , 0.0317101 , 0.08716273, 0.01651596,
       0.02470831, 0.03580574, 0.08951436, 0.01706972, 0.07347184,
       0.06906825, 0.        , 0.1268404 , 0.        , 0.09805807,
       0.01726706, 0.06470154, 0.08998425, 0.02973505, 0.09569488,
       0.02973505, 0.03494283, 0.02139802, 0.08534859, 0.03235077,
       0.08492078, 0.04539206, 0.02001602, 0.01513069, 0.        ,
       0.        , 0.03942083, 0.03379973, 0.02264554, 0.        ,
       0.02668803, 0.05063697, 0.05896397, 0.09709195, 0.09683076,
       0.01585505, 0.02973505, 0.0930726 , 0.        , 0.05741693,
       0.03053524, 0.07082882, 0.04622502, 0.07548514, 0.01228127,
       0.05120916, 0.01651596, 0.01526762, 0.04358136, 0.0203363 ,
       0.07347184, 0.06693994, 0.04441156, 0.03485075, 0.05661385,
       0.04941662, 0.0414989 , 0.05304959, 0.01069901, 0.02360961,
       0.02220578, 0.01186949, 0.1132277 , 0.        , 0.01836796,
       0.09065472, 0.        , 0.03110604, 0.03494283, 0.        ,
       0.07082882, 0.04828045, 0.04460258, 0.08841598, 0.01540834,
       0.06906825, 0.10699012, 0.0765559 , 0.05180119, 0.01726706,
       0.01726706, 0.        , 0.05574947, 0.03053524, 0.05370862,
       0.        , 0.01747141, 0.01687899, 0.03375798, 0.02001602,
       0.01651596, 0.01971041, 0.04622502, 0.09331813, 0.10016708,
       0.07767356, 0.03235077, 0.        , 0.        , 0.0877058 ,
       0.06827887, 0.01570186, 0.04721922, 0.12615514, 0.01941839,
       0.06988566, 0.04422297, 0.05161398, 0.03303192, 0.05825517,
       0.08633531, 0.02220578, 0.03942083, 0.05510388, 0.03338903,
       0.01726706, 0.02632491, 0.01971041, 0.14011213, 0.        ,
       0.        , 0.05584356, 0.03413944, 0.        , 0.02102586,
       0.02516171, 0.06661734, 0.0855921 , 0.        , 0.08268982,
       0.01513069, 0.        , 0.01747141, 0.05913124, 0.03303192,
       0.07082882, 0.04422297, 0.        , 0.07248661, 0.11440108,
       0.07927525, 0.10878566, 0.03942083, 0.        , 0.04067259,
       0.06751596, 0.06201737, 0.07776511, 0.05264981, 0.02830693,
       0.03413944, 0.07850929, 0.08257979, 0.08951436, 0.0676665 ,
       0.21025857, 0.        , 0.02948198, 0.0265046 , 0.03453413,
       0.03202563, 0.04852616, 0.08268982, 0.07595545, 0.0192077 ,
       0.06405126, 0.04696466, 0.07927525, 0.07548514, 0.02311251,
       0.03494283, 0.14891616, 0.08062594, 0.08410343, 0.08171506,
       0.03038218, 0.09705232, 0.04422297, 0.09883324, 0.05120916,
       0.12838815, 0.        , 0.03494283, 0.04622502, 0.        ,
       0.04828045, 0.06793662, 0.10318694, 0.        , 0.02360961,
       0.06537205, 0.03827795, 0.07595545, 0.01706972, 0.10127394,
       0.01706972, 0.        , 0.10741723, 0.04665906, 0.01726706,
       0.03081668, 0.01634301, 0.01687899, 0.        , 0.        ,
       0.0418121 , 0.01861452, 0.0203363 , 0.05241424, 0.05241424,
       0.04622502, 0.01836796, 0.10127394, 0.02102586, 0.        ,
       0.03626189, 0.03536639, 0.07498688, 0.02531848, 0.10148125,
       0.06677806, 0.03413944, 0.0844908 , 0.08439495, 0.12378237,
       0.08716273, 0.01449732, 0.04134491, 0.04003204, 0.06307757,
       0.0634202 , 0.06988566, 0.06004806, 0.09443843, 0.07412493,
       0.06104829, 0.04756515, 0.09855207, 0.05574947, 0.08257979,
       0.        , 0.06004806, 0.05241424, 0.08134518, 0.0265046 ,
       0.05241424, 0.01913898, 0.        , 0.06751596, 0.09058216,
       0.04529108, 0.        , 0.01836796, 0.        , 0.        ,
       0.08735707, 0.04134491, 0.01526762, 0.07082882, 0.12214096,
       0.11556254, 0.10498163, 0.02580699, 0.03026138, 0.        ,
       0.06004806, 0.        , 0.07850929, 0.01499738, 0.        ,
       0.        , 0.        , 0.02264554, 0.03453413, 0.01437993,
       0.01343766, 0.07347184, 0.05063697, 0.03453413, 0.12857571,
       0.02311251, 0.07548514, 0.10687334, 0.03140371, 0.        ,
       0.03673592, 0.06793662, 0.01601282, 0.06827887, 0.09909575,
       0.        , 0.06307757, 0.0214942 , 0.06751596, 0.01706972,
       0.04223415, 0.10878566, 0.07927525, 0.04279605, 0.01555302,
       0.03110604, 0.12403473, 0.1253201 , 0.02414023, 0.16012815,
       0.06107048, 0.13592874, 0.        , 0.01617539, 0.06793662,
       0.06100889, 0.0599895 , 0.12357788, 0.        , 0.01393737,
       0.02973505, 0.04441156, 0.04580286, 0.0765559 , 0.        ,
       0.08178608, 0.04003204, 0.01687899, 0.11098535, 0.04852616,
       0.05584356, 0.17739372, 0.20672456, 0.0549235 , 0.05825517,
       0.05241424, 0.03536639, 0.09805807, 0.04246039, 0.        ,
       0.07498688, 0.06933752, 0.02264554, 0.04441156, 0.08238526,
       0.04003204, 0.10984701, 0.12442417, 0.04852616, 0.06827887,
       0.        , 0.        , 0.09705232, 0.        , 0.06677806,
       0.02580699, 0.03774257, 0.01913898, 0.08171506, 0.02179068,
       0.06290428, 0.        , 0.03536639, 0.0176832 , 0.06100889,
       0.03053524, 0.        , 0.07595545, 0.        , 0.06410256,
       0.05195243, 0.08006408, 0.01887128, 0.03303192, 0.07161149,
       0.09435642, 0.01570186, 0.11168712, 0.12988108, 0.0405999 ,
       0.01971041, 0.        , 0.04279605, 0.08087693, 0.        ,
       0.01404417, 0.01669451, 0.        , 0.06827887, 0.        ,
       0.03314968, 0.1110289 , 0.01461763, 0.05008354, 0.01316245,
       0.08134518, 0.10512928, 0.01513069, 0.08951436, 0.        ,
       0.09435642, 0.08257979, 0.        , 0.06751596, 0.11440108,
       0.0176832 , 0.01437993, 0.        , 0.01343766, 0.02414023,
       0.11826248, 0.01634301, 0.0421325 , 0.03774257, 0.10878566,
       0.05337605, 0.        , 0.        , 0.03871048, 0.1253201 ,
       0.08006408, 0.05304959, 0.04460258, 0.0203363 , 0.07445808,
       0.01706972, 0.08347257, 0.        , 0.05063697, 0.03827795,
       0.02414023, 0.04279605, 0.01836796, 0.04279605, 0.05375062,
       0.02746175, 0.14153463, 0.08841598, 0.02899464, 0.        ,
       0.08347257, 0.03453413, 0.03338903, 0.1315587 , 0.03580574,
       0.0176832 , 0.12615514, 0.06537205, 0.02264554, 0.14504754,
       0.04441156, 0.04622502, 0.01887128, 0.05304959, 0.16112585,
       0.        , 0.01617539, 0.        , 0.01651596, 0.04484485,
       0.        , 0.03026138, 0.1132277 , 0.07007128, 0.11826248,
       0.01913898, 0.        , 0.        , 0.01706972, 0.        ,
       0.05008354, 0.01887128, 0.03235077, 0.        , 0.01437993,
       0.01836796, 0.02668803, 0.        , 0.03413944, 0.08134518,
       0.01393737, 0.04954787, 0.02311251, 0.02597622, 0.02597622,
       0.01861452, 0.        , 0.        , 0.08087693, 0.09078413,
       0.10895341, 0.04089304, 0.09065472, 0.01601282, 0.05063697,
       0.0418121 , 0.01813094, 0.        , 0.02102586, 0.05439283,
       0.08439495, 0.04067259, 0.06677806, 0.03338903, 0.04134491,
       0.02360961, 0.02220578, 0.0176832 , 0.07347184, 0.08699849,
       0.04622502, 0.08410343, 0.03338903, 0.05741693, 0.08439495,
       0.04279605, 0.05120916, 0.02287545, 0.        , 0.02766593,
       0.10390487, 0.04441156, 0.05304959, 0.01585505, 0.0203363 ,
       0.11020775, 0.05241424, 0.04358136, 0.11948803, 0.05304959,
       0.04067259, 0.05241424, 0.10127394, 0.07248661, 0.05510388,
       0.09183979, 0.        , 0.07792865, 0.08534859, 0.05375062,
       0.08410343, 0.04529108, 0.04205171, 0.03942083, 0.12009612,
       0.11826248, 0.14235407, 0.03338903, 0.02139802, 0.03140371,
       0.10148125, 0.10168148, 0.06100889, 0.12393235, 0.06677806,
       0.0765559 , 0.06988566, 0.02067246, 0.08439495, 0.06933752,
       0.02899464, 0.04205171, 0.08171506, 0.10390487, 0.07767356,
       0.04756515, 0.06307757, 0.06537205, 0.        , 0.04134491,
       0.01393737, 0.1132277 , 0.12615514, 0.05337605, 0.09183979,
       0.01393737, 0.06815507, 0.03494283, 0.02668803, 0.04499213,
       0.09569488, 0.10360238, 0.03413944, 0.01813094, 0.08268982,
       0.        , 0.01540834, 0.01499738, 0.        , 0.07792865,
       0.06163336, 0.06751596, 0.03942083, 0.05195243, 0.02597622,
       0.10336228, 0.08238526, 0.03942083, 0.05751973, 0.05741693,
       0.01941839, 0.08238526, 0.        , 0.02179068, 0.08951436,
       0.03536639, 0.11208971, 0.08841598, 0.05195243, 0.1132277 ,
       0.03026138, 0.01634301, 0.08882312, 0.0549235 , 0.14146557,
       0.02067246, 0.01747141, 0.13074409, 0.07132675, 0.01513069,
       0.10699012, 0.        , 0.16269037, 0.11556254, 0.01651596,
       0.        , 0.        , 0.02441931, 0.02139802, 0.10016708,
       0.02360961, 0.04067259, 0.04205171, 0.        , 0.04721922,
       0.06537205, 0.02264554, 0.02179068, 0.05180119, 0.01813094,
       0.02001602, 0.08268982, 0.        , 0.03268602, 0.08882312,
       0.02311251, 0.1067521 , 0.10336228, 0.05510388, 0.04756515,
       0.05370862, 0.01726706, 0.01971041, 0.11556254, 0.10741723,
       0.13867505, 0.        , 0.        , 0.13587324, 0.        ,
       0.08410343, 0.04422297, 0.03494283, 0.06221208, 0.02179068,
       0.01971041, 0.06470154, 0.05452405, 0.06307757, 0.03140371,
       0.04580286, 0.0855921 , 0.08006408, 0.03827795, 0.08806599,
       0.04279605, 0.08841598, 0.03413944, 0.03202563, 0.01155625,
       0.03081668, 0.07252377, 0.04529108, 0.02999475, 0.04067259,
       0.04622502, 0.05063697, 0.05870583, 0.0319547 , 0.07704169,
       0.0877058 , 0.03536639, 0.01499738, 0.        , 0.0203363 ,
       0.0951303 , 0.02973505, 0.        , 0.06815507, 0.03413944,
       0.05370862, 0.        , 0.06201737, 0.0530092 , 0.09760722,
       0.        , 0.0765559 , 0.05337605, 0.06537205, 0.0203363 ,
       0.03942083, 0.05681146, 0.0634202 , 0.04954787, 0.09705232,
       0.06419407, 0.08006408, 0.14891616, 0.01887128, 0.0317101 ,
       0.09443843, 0.02470831, 0.18490007, 0.        , 0.06793662,
       0.0317101 , 0.04358136, 0.08951436, 0.        , 0.07347184,
       0.        , 0.        , 0.05847053, 0.02067246, 0.02470831,
       0.02001602, 0.        , 0.        , 0.01861452, 0.02311251,
       0.05913124, 0.0662615 , 0.05063697, 0.03053524, 0.04279605,
       0.04003204, 0.03673592, 0.03026138, 0.12378237, 0.16537965,
       0.01747141, 0.        , 0.17432545, 0.03673592, 0.0599895 ,
       0.03673592, 0.        , 0.04003204, 0.05229764, 0.04349197,
       0.03140371, 0.02830693, 0.04721922, 0.05439283, 0.0765559 ,
       0.10127394, 0.06988566, 0.13209899, 0.        , 0.        ,
       0.04349197, 0.07850929, 0.05120916, 0.15025063, 0.05337605,
       0.0765559 , 0.10878566, 0.02597622, 0.        , 0.02973505,
       0.11168712, 0.06677806, 0.03110604, 0.        , 0.04003204,
       0.02102586, 0.08087693, 0.        , 0.03202563, 0.        ,
       0.01415346, 0.09909575, 0.01913898, 0.03922323, 0.04721922,
       0.04665906, 0.04941662, 0.03774257, 0.01790287, 0.07445808,
       0.06201737, 0.0951303 , 0.09065472, 0.03536639, 0.12070114,
       0.0930726 , 0.06815507, 0.15701857, 0.09883324, 0.01971041,
       0.06004806, 0.02067246, 0.02948198, 0.01669451, 0.08238526,
       0.        , 0.1381365 , 0.12201778, 0.20218928, 0.04441156,
       0.03948736, 0.08134518, 0.02668803, 0.02360961, 0.13849851,
       0.09078413, 0.06470154, 0.0203363 , 0.        , 0.06201737,
       0.02220578, 0.        , 0.        , 0.01499738, 0.01747141,
       0.09705232, 0.08006408, 0.03774257, 0.05661385, 0.02001602,
       0.09805807, 0.03303192, 0.06307757, 0.04279605, 0.09805807,
       0.06052275, 0.08006408, 0.04721922, 0.02360961, 0.08844595,
       0.06718828, 0.05229764, 0.07792865, 0.06405126, 0.01913898,
       0.03883678, 0.02668803, 0.03580574, 0.05304959, 0.02360961,
       0.07082882, 0.05241424, 0.0176832 , 0.        , 0.03580574,
       0.05063697, 0.02414023, 0.05120916, 0.02597622, 0.04003204,
       0.01790287, 0.        , 0.06661734, 0.02948198, 0.06307757,
       0.03026138, 0.02531848, 0.02441931, 0.02531848, 0.05195243,
       0.08410343, 0.02067246, 0.04941662, 0.01437993, 0.03774257,
       0.06107048, 0.02441931, 0.05063697, 0.04721922, 0.04941662,
       0.04031297, 0.07792865, 0.11651035, 0.09435642, 0.06793662,
       0.04828045, 0.04941662, 0.04279605, 0.05337605, 0.0599895 ,
       0.01449732, 0.02001602, 0.        , 0.09245003, 0.02264554,
       0.06329621, 0.06419407, 0.02179068, 0.04902903, 0.09065472,
       0.08347257, 0.07082882, 0.03494283, 0.07082882, 0.05574947,
       0.        , 0.02597622, 0.05063697, 0.04941662, 0.01941839,
       0.13631014, 0.02220578, 0.03883678, 0.05008354, 0.02808834,
       0.        , 0.        , 0.        , 0.0549235 , 0.02787473,
       0.30194054, 0.32025631, 0.04279605, 0.10241831, 0.04134491,
       0.01747141, 0.04205171, 0.05264981, 0.03338903, 0.04721922,
       0.07242068, 0.11894021, 0.0549235 , 0.        , 0.        ,
       0.04349197, 0.14146557, 0.02311251, 0.        , 0.0176832 ,
       0.0270666 , 0.02597622, 0.05439283, 0.0203363 , 0.05510388,
       0.01726706, 0.02999475, 0.        , 0.02470831, 0.07792865,
       0.        , 0.0132523 , 0.0431398 , 0.        , 0.        ,
       0.        , 0.09245003, 0.01706972, 0.01669451, 0.06793662,
       0.12201778, 0.08426501, 0.01913898, 0.03600634, 0.02102586,
       0.        , 0.04941662, 0.01706972, 0.03827795, 0.        ,
       0.04134491, 0.06100889, 0.03626189, 0.05195243, 0.1268404 ,
       0.06968683, 0.02001602, 0.        , 0.03942083, 0.13323468,
       0.18681618, 0.12838815, 0.04089304, 0.08134518, 0.05718863,
       0.        , 0.04003204, 0.06004806, 0.01540834, 0.07850929,
       0.06307757, 0.09421114, 0.        , 0.10984701, 0.1132277 ,
       0.0421325 , 0.10168148, 0.04067259, 0.        , 0.07548514,
       0.02830693, 0.06280743, 0.04852616, 0.        , 0.02067246,
       0.05510388, 0.0352235 , 0.10741723, 0.04460258, 0.03883678,
       0.11020775, 0.10065953, 0.08806599, 0.09705232, 0.04721922,
       0.02999475, 0.01813094, 0.05180119, 0.10318694, 0.13266892,
       0.08238526, 0.01971041, 0.02360961, 0.03338903, 0.06100889,
       0.08410343, 0.09805807, 0.05120916, 0.        , 0.03883678,
       0.04358136, 0.07161149, 0.14824986, 0.01220966, 0.02668803,
       0.02875987, 0.04205171, 0.        , 0.02414023, 0.02311251,
       0.01813094, 0.14891616, 0.09058216, 0.05128205, 0.07412493,
       0.05063697, 0.1000801 , 0.09012156, 0.10336228, 0.04279605,

In [ ]:
!free -h

               total        used        free      shared  buff/cache   available
Mem:            12Gi       1.6Gi       5.7Gi       1.0Mi       5.4Gi        10Gi
Swap:             0B          0B          0B

In [ ]:
newdf[newdf["title"]=="Avatar"].index

Index([0], dtype='object')

In [ ]:
newdf[newdf["title"]=="Avatar"].index[0]

0

In [ ]:
sorted(enumerate(similarity[0]),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.2503866978335957))]

In [ ]:
def recommend(movie):
  movie_index=newdf[newdf["title"]==movie].index[0]
  distances=similarity[movie_index]
  new_list=sorted(enumerate(distances),reverse=True,key=lambda x:x[1])[1:6]
  for i in new_list:
    print(newdf.iloc[i[0]].title)

In [ ]:
recommend("Batman Begins")

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [ ]:
recommend("John Carter")

Riddick
Krrish
The Other Side of Heaven
The Legend of Hercules
Get Carter

In [ ]:
recommend("Pirates of the Caribbean: At World's End")

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
Life of Pi
20,000 Leagues Under the Sea

In [ ]:
recommend("Spider-Man 3")

Spider-Man 2
Spider-Man
The Amazing Spider-Man 2
The Amazing Spider-Man
Arachnophobia

In [ ]:
recommend("Avengers: Age of Ultron")

Iron Man 3
Iron Man 2
Iron Man
Thor
The Avengers

In [ ]:
recommend("Harry Potter and the Half-Blood Prince")

Harry Potter and the Order of the Phoenix
Harry Potter and the Goblet of Fire
Harry Potter and the Chamber of Secrets
Harry Potter and the Philosopher's Stone
Harry Potter and the Prisoner of Azkaban

In [ ]:
recommend("Man of Steel")

Superman Returns
Superman II
X-Men: First Class
Ong Bak 2
Jupiter Ascending

In [ ]:
import pickle

In [ ]:
pickle.dump(newdf,open("movies.pkl","wb"))

In [ ]:
newdf.to_dict()

In [ ]:
pickle.dump(newdf.to_dict(),open("movies_dict.pkl","wb"))

In [ ]:
pickle.dump(similarity,open("similarity.pkl","wb"))

In [ ]:
newdf

,id,title,tags
0,19995.0,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285.0,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647.0,Spectre,a cryptic messag from bond’ past send him on a...
3,49026.0,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529.0,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4805,72766.0,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617.0,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186.0,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975.0,My Date with Drew,ever sinc the second grade when he first saw h...
tags,NaN,NaN,nan